import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UseLang from "./_hooks/UseLang/UseLang";
import Navbar from "./_components/templates/Navbar";
import 'bootstrap-icons/font/bootstrap-icons.min.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LovelCode/لاول کد",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="fa">
      <body className={`${inter.className} bg-background text-white`}>
        <div className="font-yekanbakh">
          <Navbar></Navbar>
          <div className="">
          {children}
          </div>
        </div>
      </body>
      <UseLang></UseLang>
    </html>
  );
}
