import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.min.css";
import Topbar from "../_components/templates/topbar/Topbar";
import { NextIntlClientProvider, useMessages } from "next-intl";
import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });
const yekanbakh = localFont({
  src: [
    {
      path: "../_fonts/fonts/woff/yekanbakh-Light.woff",
      weight: "300",
    },
    {
      path: "../_fonts/fonts/woff/YekanBakh-Regular.woff",
      weight: "400",
    },
  ],
  variable: "--font-yekanbakh",
  weight: "400",
});
const cinema = localFont({
  src: "../_fonts/fonts/Cinema Font ( www.rezagraphic.ir ).ttf",
  variable: "--font-cinema",
});
export const metadata: Metadata = {
  title: "LovelCode/لاول کد",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();
  return (
    <html
      dir={locale === "fa" ? "rtl" : locale === "en" ? "ltr" : "rtl"}
      className=""
      lang={locale}
    >
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body
          className={`${cinema.variable} ${yekanbakh.variable} bg-background text-white font-yekanbakh`}
        >
          <div className="">
            <Topbar></Topbar>
            <div className="">{children}</div>
          </div>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
